"""add editorial reason to clips

Revision ID: 83edb3e589ef
Revises: 6b248bce5f8c
Create Date: 2026-09-25 16:29:22.122091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83edb3e589ef'
down_revision: Union[str, Sequence[str], None] = '6b248bce5f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "clips",
        sa.Column("editorial_reason", sa.Text(), nullable=True),
    )
    op.execute(
        "UPDATE clips "
        "SET editorial_reason = 'Propuesta creada antes de registrar una razón editorial.' "
        "WHERE editorial_reason IS NULL"
    )
    op.alter_column("clips", "editorial_reason", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'editorial_reason')
    # ### end Alembic commands ###
