"""add video storage metadata

Revision ID: df355a877f46
Revises: 213902a44b70
Create Date: 2026-09-24 15:19:01.979966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df355a877f46'
down_revision: Union[str, Sequence[str], None] = '213902a44b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_video_path', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'file_size_bytes')
    op.drop_column('jobs', 'source_video_path')
    # ### end Alembic commands ###
